# Generated by Django 4.0.1 on 2022-02-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_alter_phone_options_phone_count_alter_phone_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.CharField(max_length=25, null=True, verbose_name='Цена'),
        ),
    ]
